name = "QNM"
uuid = "67afd3b9-d5e3-4448-a824-f75cdcbb779e"
authors = ["Finn Wagner <finn.jannik.wagner@physik.uni-giessen.de"]
version = "0.1.0"

[deps]
BoundaryValueDiffEq = "764a87c0-6b3e-53db-9096-fe964310641d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
BoundaryValueDiffEq = "2.11.0"
DifferentialEquations = "7.7.0"
OrdinaryDiffEq = "6.44.1"
